# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\PycharmProjects\MixingSessionSetup\GUI\DesignerFiles\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.newSessionLocationLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newSessionLocationLineEdit.setObjectName("newSessionLocationLineEdit")
        self.gridLayout_3.addWidget(self.newSessionLocationLineEdit, 8, 0, 1, 1)
        self.newSessionLocationToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.newSessionLocationToolButton.setObjectName("newSessionLocationToolButton")
        self.gridLayout_3.addWidget(self.newSessionLocationToolButton, 8, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 2)
        self.newSessionNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newSessionNameLineEdit.setObjectName("newSessionNameLineEdit")
        self.gridLayout_3.addWidget(self.newSessionNameLineEdit, 10, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 2)
        self.oldSessionLocationLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.oldSessionLocationLineEdit.setClearButtonEnabled(False)
        self.oldSessionLocationLineEdit.setObjectName("oldSessionLocationLineEdit")
        self.gridLayout_3.addWidget(self.oldSessionLocationLineEdit, 5, 0, 1, 1)
        self.sessionTemplateLocationToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.sessionTemplateLocationToolButton.setObjectName("sessionTemplateLocationToolButton")
        self.gridLayout_3.addWidget(self.sessionTemplateLocationToolButton, 3, 1, 1, 1)
        self.makeNewSessionPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.makeNewSessionPushButton.setObjectName("makeNewSessionPushButton")
        self.gridLayout_3.addWidget(self.makeNewSessionPushButton, 11, 0, 1, 2)
        self.oldSessionLocationToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.oldSessionLocationToolButton.setObjectName("oldSessionLocationToolButton")
        self.gridLayout_3.addWidget(self.oldSessionLocationToolButton, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 12, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 9, 0, 1, 1)
        self.sessionTemplateLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sessionTemplateLineEdit.setObjectName("sessionTemplateLineEdit")
        self.gridLayout_3.addWidget(self.sessionTemplateLineEdit, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scriptTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.scriptTextBrowser.setObjectName("scriptTextBrowser")
        self.gridLayout.addWidget(self.scriptTextBrowser, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.celtxScriptsListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.celtxScriptsListWidget.setObjectName("celtxScriptsListWidget")
        self.gridLayout.addWidget(self.celtxScriptsListWidget, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1)
        self.makeSFXListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.makeSFXListPushButton.setObjectName("makeSFXListPushButton")
        self.gridLayout.addWidget(self.makeSFXListPushButton, 8, 1, 1, 1)
        self.populateCeltxPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.populateCeltxPushButton.setObjectName("populateCeltxPushButton")
        self.gridLayout.addWidget(self.populateCeltxPushButton, 8, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 5, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.emailAddressLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.emailAddressLineEdit.setObjectName("emailAddressLineEdit")
        self.horizontalLayout.addWidget(self.emailAddressLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 2, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.setupPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupPushButton.sizePolicy().hasHeightForWidth())
        self.setupPushButton.setSizePolicy(sizePolicy)
        self.setupPushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.setupPushButton.setFont(font)
        self.setupPushButton.setObjectName("setupPushButton")
        self.gridLayout_4.addWidget(self.setupPushButton, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 3)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 0, 1, 3)
        self.gridLayout_2.setColumnStretch(0, 4)
        self.gridLayout_2.setColumnStretch(2, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sessionTemplateLineEdit, self.sessionTemplateLocationToolButton)
        MainWindow.setTabOrder(self.sessionTemplateLocationToolButton, self.oldSessionLocationLineEdit)
        MainWindow.setTabOrder(self.oldSessionLocationLineEdit, self.oldSessionLocationToolButton)
        MainWindow.setTabOrder(self.oldSessionLocationToolButton, self.newSessionLocationLineEdit)
        MainWindow.setTabOrder(self.newSessionLocationLineEdit, self.newSessionLocationToolButton)
        MainWindow.setTabOrder(self.newSessionLocationToolButton, self.makeNewSessionPushButton)
        MainWindow.setTabOrder(self.makeNewSessionPushButton, self.celtxScriptsListWidget)
        MainWindow.setTabOrder(self.celtxScriptsListWidget, self.scriptTextBrowser)
        MainWindow.setTabOrder(self.scriptTextBrowser, self.populateCeltxPushButton)
        MainWindow.setTabOrder(self.populateCeltxPushButton, self.makeSFXListPushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Setup Mixing Session"))
        self.newSessionLocationToolButton.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "New Session Location:"))
        self.label_6.setText(_translate("MainWindow", "Make New Mixing Session:"))
        self.label_3.setText(_translate("MainWindow", "Session Template Location:"))
        self.label_4.setText(_translate("MainWindow", "Old Session Location:"))
        self.sessionTemplateLocationToolButton.setText(_translate("MainWindow", "..."))
        self.makeNewSessionPushButton.setText(_translate("MainWindow", "Make New Session"))
        self.oldSessionLocationToolButton.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "New Session Name:"))
        self.label_7.setText(_translate("MainWindow", "Generate SFX List:"))
        self.label.setText(_translate("MainWindow", "Celtx Scripts:"))
        self.label_2.setText(_translate("MainWindow", "Script:"))
        self.makeSFXListPushButton.setText(_translate("MainWindow", "Make SFX List from Script"))
        self.populateCeltxPushButton.setText(_translate("MainWindow", "Populate"))
        self.label_11.setText(_translate("MainWindow", "(Optional) Email Address:"))
        self.label_9.setText(_translate("MainWindow", "Setup Mixing Session:"))
        self.label_10.setText(_translate("MainWindow", "Make sure all the required fields are filled out and you have selected a script from the list"))
        self.setupPushButton.setText(_translate("MainWindow", "Setup"))
